### ISSUE TITLE
Hello, its Davis

### ISSUE THREAD

**Issue by Longwater1234** [mafaro21/Nssa#1]
man, it's been a while. you are alive? Do you still use wechat? Or imessage?

**Comment by mafaro21** [comment]
yo bro, im good man
how you been?
don't use wechat you can try whatsapp

**Comment by Longwater1234** [comment]
@mafaro21 My whatsapp is long dead

**Comment by mafaro21** [comment]
Bro...
What happened
So you use iMessage?

**Comment by Longwater1234** [comment]
yes i use imessage, same number. i dont know i cannot login since 2018
